const stateobject = [{
  data:[{
    placeholder:"Character Name",
    value:"Light Scratch",
    disabled:false,
    classes:'',
    id:"ID0001",
    suggestions:[],
    raiseLabel:true,
    classes:"",
  },{
    placeholder:"Class & Level",
    value:"Paladin",
    disabled:false,
    classes:'',
    id:"ID0002",
    suggestions:["Paladin", "Ranger", "Rogue", "Wizard", "Monk", "Sorcerer", "Barbarian"],
    raiseLabel:true,
    classes:"",
  },{
    placeholder:"Class & Level",
    value:"Paladin",
    disabled:false,
    classes:'',
    id:"ID0002",
    suggestions:[],
    raiseLabel:true,
    classes:"",
  },{
    placeholder:"Class & Level",
    value:"Paladin",
    disabled:false,
    classes:'',
    id:"ID0002",
    suggestions:[],
    raiseLabel:true,
    classes:"",
  },{
    placeholder:"Class & Level",
    value:"Paladin",
    disabled:false,
    classes:'',
    id:"ID0002",
    suggestions:[],
    raiseLabel:true,
    classes:"",
  },{
    placeholder:"Class & Level",
    value:"Paladin",
    disabled:false,
    classes:'',
    id:"ID0002",
    suggestions:[],
    raiseLabel:true,
    classes:"",
  },{
    placeholder:"Class & Level",
    value:"Paladin",
    disabled:false,
    classes:'',
    id:"ID0002",
    suggestions:[],
    raiseLabel:true,
    classes:"",
  },{
    placeholder:"Class & Level",
    value:"Paladin",
    disabled:false,
    classes:'',
    id:"ID0002",
    suggestions:[],
    raiseLabel:true,
    classes:"",
  },{
    placeholder:"Class & Level",
    value:"Paladin",
    disabled:false,
    classes:'',
    id:"ID0002",
    suggestions:[],
    raiseLabel:true,
    classes:"",
  }],
  width:5,
  category:'basicinfo',
  maptype:'InputFieldContainer',
  standardwidth:'fifth',
  alignment:'row',
}]
export default stateobject;
